ContosoUniversity/ContosoUniversity/Models/Activity.cs
using System;
using System.Collections.Generic;


namespace ContosoUniversity.Models
{
    public class Activity 
    {
        public int ID { get; set; }
        public string ActivityName { get; set; }
        public DateTime ActivityDate { get; set; }

        public virtual ApplicationUser User { get; set; }
    }
}

ContosoUniversity/ContosoUniversity/Controllers/ActivityController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ContosoUniversity.Models;
using PagedList;

namespace ContosoUniversity.Controllers
{
    public class ActivityController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Activity
        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {

            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            //var userLogin = HttpContext.Current.User.Identity.Name;


            // var students = from s in db.Students
            //   select s;


            var usersActivities = db.Activities.Where(us => us.User.Email == User.Identity.Name).ToList();

            if (!String.IsNullOrEmpty(searchString)) // do wyszukiwania
            {
                usersActivities = usersActivities.Where(s => s.ActivityName.Contains(searchString)).ToList();
            }
            switch (sortOrder)
            {
                case "name_desc":
                    usersActivities = usersActivities.OrderByDescending(s => s.ActivityName).ToList();
                    break;
                case "Date":
                    usersActivities = usersActivities.OrderBy(s => s.ActivityDate).ToList();
                    break;
                case "date_desc":
                    usersActivities = usersActivities.OrderByDescending(s => s.ActivityDate).ToList();
                    break;
                default:
                    usersActivities = usersActivities.OrderBy(s => s.ActivityName).ToList();
                    break;
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(usersActivities.ToPagedList(pageNumber, pageSize));
            // return View(db.Activities.ToList());
        }

        // GET: Activity/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Activity activity = db.Activities.Find(id);
            if (activity == null)
            {
                return HttpNotFound();
            }
            return View(activity);
        }

        // GET: Activity/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Activity/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,ActivityName,ActivityDate")] Activity activity)
        {
            
            if (ModelState.IsValid)
            {
                activity.User = db.Users.First(u => u.Email == User.Identity.Name);
                db.Activities.Add(activity);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(activity);
        }

        // GET: Activity/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Activity activity = db.Activities.Find(id);
            if (activity == null)
            {
                return HttpNotFound();
            }
            return View(activity);
        }

        // POST: Activity/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,ActivityName,ActivityDate")] Activity activity)
        {
            if (ModelState.IsValid)
            {
                db.Entry(activity).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(activity);
        }

        // GET: Activity/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Activity activity = db.Activities.Find(id);
            if (activity == null)
            {
                return HttpNotFound();
            }
            return View(activity);
        }

        // POST: Activity/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Activity activity = db.Activities.Find(id);
            db.Activities.Remove(activity);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ContosoUniversity/ContosoUniversity/Views/Activity/Create.cshtml
<link rel="stylesheet" href="~/Content/calendar.css">
@model ContosoUniversity.Models.Activity

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Activity</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ActivityName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ActivityName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ActivityName, "", new { @class = "text-danger" })
            </div>
        </div>
<!--
        <div class="form-group">
            @Html.LabelFor(model => model.ActivityDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ActivityDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ActivityDate, "", new { @class = "text-danger" })
            </div>
        </div>
    -->
        
        <div class="form-group">
            <label class="control-label col-md-2" for="ActivityDate">ActivityDate</label>
            <div class="col-md-10">
                <input id="time" type="time">  
                <input class="input-demo7" data-val="true" data-val-date="The field ActivityDate must be a date." data-val-required="Pole ActivityDate jest wymagane." id="ActivityDate" name="ActivityDate" type="datetime" value="" />
                <span class="field-validation-valid text-danger" data-valmsg-for="ActivityDate" data-valmsg-replace="true"></span>
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>





<p class="demo7">
    <input type="text" class="input-demo7" style="display:none;">
    <span class="demo7-text" style="display:none;"></span>
</p>

<p>
    <input type="text" class="input-demo6" style="display:none;">
</p>



<script>
(function() {
    function Calendar(input, options) {
        this.now = new Date();
        this.day = this.now.getDate();
        this.month = this.now.getMonth();
        this.year = this.now.getFullYear();
        this.input = input;
        this.divCnt = null;
        this.divTable = null;
        this.divDateText = null;
        this.divButtons = null;

        const defaultOptions = {
            closeOnSelect : false,
            onDateSelect : function(day, month, year) {
                const monthText = ((month + 1) < 10) ? "0" + (month + 1) : month + 1;
                const dayText =  (day < 10) ? "0" + day : day;
                this.input.value = dayText + '-' + monthText + '-' + this.year;
            }.bind(this)
        }
        this.options = Object.assign({}, defaultOptions, options);

        this.createDateText = function () {
            const monthNames = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

            //tworzymy nazwę miesiąca

            this.divDateText.innerHTML = monthNames[this.month] + ' ' + this.year; //czyscimy zawartosc diva
        };

        //metoda tworząca guziczki
        this.createButtons = function () {
            const buttonPrev = document.createElement('button');
            buttonPrev.innerText = '<';
            buttonPrev.type = "button";
            buttonPrev.classList.add('input-prev');
            buttonPrev.addEventListener('click', function () {
                this.month--;
                if (this.month < 0) {
                    this.month = 11;
                    this.year--;
                }
                this.createCalendarTable();
                this.createDateText();
            }.bind(this));
            this.divButtons.appendChild(buttonPrev);

            const buttonNext = document.createElement('button');
            buttonNext.classList.add('input-next');
            buttonNext.innerText = '>';
            buttonNext.type = "button";
            buttonNext.addEventListener('click', function () {
                this.month++;
                if (this.month > 11) {
                    this.month = 0;
                    this.year++;
                }
                this.createCalendarTable();
                this.createDateText();
            }.bind(this));
            this.divButtons.appendChild(buttonNext);
        };

        this.bindTableDaysEvent = function() {
            this.divTable.addEventListener('click', function(e) {

                if (e.target.tagName.toLowerCase() === 'td' && e.target.classList.contains('day')) {
                    if (this.options.closeOnSelect) {
                        this.hide();
                    }
                    this.options.onDateSelect(e.target.dayNr, this.month + 1, this.year);
                }

            }.bind(this));
        };

        //metoda tworzaca tabele z kalendarzem
        this.createCalendarTable = function () {
            this.divTable.innerHTML = '';

            //tworzymy nazwy dni
            const tab = document.createElement('table');
            tab.classList.add('calendar-table');

            //tworzymy naglowki dni
            let tr = document.createElement('tr');
            tr.classList.add('calendar-table-days-names')
            const days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
            for (let i=0; i<days.length; i++) {
                const th = document.createElement('th');
                th.innerHTML = days[i];
                tr.appendChild(th);
            }
            tab.appendChild(tr);

            //tworzymy rzędy dni
            const daysInMonth = new Date(this.year, this.month+1, 0).getDate();

            const tempDate = new Date(this.year, this.month, 1);
            let firstMonthDay = tempDate.getDay();

            if (firstMonthDay === 0) {
                firstMonthDay = 7;
            }

            const j = daysInMonth + firstMonthDay - 1;

            if (firstMonthDay - 1 !== 0) {
                tr = document.createElement('tr');
                tab.appendChild(tr);
            }

            for (let i=0; i < firstMonthDay - 1; i++) {
                const td = document.createElement('td');
                td.innerHTML = '';
                tr.appendChild(td);
            }

            for (let i = firstMonthDay-1; i<j; i++) {
                if((i % 7) == 0){
                    tr = document.createElement('tr');
                    tab.appendChild(tr);
                }

                const td = document.createElement('td');
                td.innerText = i - firstMonthDay + 2;
                td.dayNr = i - firstMonthDay + 2;
                td.classList.add('day');

                if (this.year === this.now.getFullYear() && this.month === this.now.getMonth() && this.day === i - firstMonthDay + 2) {
                    td.classList.add('current-day')
                }

                tr.appendChild(td);
            }

            tab.appendChild(tr);

            this.divTable.appendChild(tab);
        };

        this.toggleShow = function() {
            this.divCnt.classList.toggle('calendar-show');
        }

        this.show = function() {
            this.divCnt.classList.add('calendar-show');
        }

        this.hide = function() {
            this.divCnt.classList.remove('calendar-show');
        }

        //metoda inicjujaca obiekt
        this.init = function () {
            //tworzymy div z całą zawartością
            this.divCnt = document.createElement('div');
            this.divCnt.classList.add('calendar');

            //tworzymy wrapper dla input
            this.calendarWrapper = document.createElement('div');
            this.calendarWrapper.classList.add('input-calendar-cnt');
            this.input.parentElement.insertBefore(this.calendarWrapper, this.input);
            this.calendarWrapper.appendChild(this.input);

            //tworzymy div z guzikami
            this.divButtons = document.createElement('div');
            this.divButtons.className = "calendar-prev-next";
            this.createButtons();

            //tworzymy div z nazwą miesiąca
            this.divDateText = document.createElement('div');
            this.divDateText.className = 'date-name';

            this.divHeader = document.createElement('div');
            this.divHeader.classList.add('calendar-header');

            this.divHeader.appendChild(this.divButtons);
            this.divHeader.appendChild(this.divDateText);
            this.divCnt.appendChild(this.divHeader);
            this.createDateText();

            //tworzymy div z tabelą.calendara
            this.divTable = document.createElement('div');
            this.divTable.className = 'calendar-table-cnt';
            this.divCnt.appendChild(this.divTable);
            this.createCalendarTable();
            this.bindTableDaysEvent();

            this.input.classList.add('input-calendar');
            this.input.addEventListener('click', function() {
                this.toggleShow();
            }.bind(this));


            this.input.addEventListener('click', function(e) {
                e.stopImmediatePropagation();
            });
            this.divCnt.addEventListener('click', function(e) {
                e.stopImmediatePropagation();
            });

            document.addEventListener('click', function() {
                this.hide();
            }.bind(this));

            //nasz div z zawartością wrzucamy na koniec body
            this.calendarWrapper.appendChild(this.divCnt);
        };
    };

    //metoda dla inputwo - zamienia inputy na kalendarzowe
    const inp1 = document.querySelector('.input-demo6');
    //dla 1 inputa wyłączam tylko zamykanie przy wyborze daty
    const opt1 = {
        closeOnSelect : false
    }
    const cal1 = new Calendar(inp1, opt1);
    cal1.init();


    const inp2 = document.querySelector('.input-demo7');
    //dla 2 inputa nadpisuję tylko akcję po wyborze daty
    const opt2 = {
        closeOnSelect : true,
        onDateSelect : function(day, month, year) {
            const dayText = (day < 10) ? '0' + day : day;
            const monthText = (month < 10) ? '0' + month : month;

            var Hour = document.getElementById("time");

            const date = year + '.' + monthText + '.' + dayText + " " + Hour.value;
            document.querySelector('.demo7-text').innerHTML = 'You have chosen the date: <strong>' + date + '</strong>';
            inp2.value = date;
        }
    }
    const cal2 = new Calendar(inp2, opt2);
    cal2.init();
})();
</script>

ContosoUniversity/ContosoUniversity/Views/Activity/Delete.cshtml
@model ContosoUniversity.Models.Activity

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Activity</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ActivityName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActivityName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ActivityDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActivityDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ContosoUniversity/ContosoUniversity/Views/Activity/Details.cshtml
@model ContosoUniversity.Models.Activity

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Activity</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ActivityName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActivityName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ActivityDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActivityDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ContosoUniversity/ContosoUniversity/Views/Activity/Edit.cshtml
@model ContosoUniversity.Models.Activity

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Activity</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.ActivityName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ActivityName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ActivityName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ActivityDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ActivityDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ActivityDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ContosoUniversity/ContosoUniversity/Views/Activity/Index.cshtml
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@model PagedList.IPagedList<ContosoUniversity.Models.Activity>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>


@using (Html.BeginForm("Index", "Activity", FormMethod.Get))
{
    <p>
        Find action: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}

<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Activity", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("When", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ActivityName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ActivityDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

<br />
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))